# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://talebagha.com
baseurl: /sustain/
title: Abdul Talebagha
author: Abdul Talebagha
description: Personal site and resume
avatar: Profile.png
email: abdul@talebagha.com
github: atalebagha # username
twitter: atalebagha
linkedin: atalebagha
stackoverflow: atalebagha   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: atalebagha
google_analytics:


# needed for travis-ci build
exclude: [vendor]
